config/routes.rb
Rails.application.routes.draw do
  resources :tareas
  devise_for :users
  root to: 'tareas#index'
  get '/completar/:id', to: 'tareas#completar', as: 'completar' #para llamar rutas desde index
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tarea.rb
class Tarea < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_and_belongs_to_many :tareas

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  before_action :set_tarea, only: [:completar, :show, :edit, :update, :destroy]

  # GET /tareas
  # GET /tareas.json
  def index
    @tareas = Tarea.all
  end

  # GET /tareas/1
  # GET /tareas/1.json
  def show
    @ranking = @tarea.users.order(:created_at).limit(5)
  end

  # GET /tareas/new
  def new
    @tarea = Tarea.new
  end

  # GET /tareas/1/edit
  def edit
  end

  def completar
      @tarea = Tarea.find(params[:id])
      if (@tarea.users.include?(current_user))
        @tarea.users.destroy(current_user)
      else
        @tarea.users << current_user
      end
      @tarea.save
      redirect_to root_path
    end


  # POST /tareas
  # POST /tareas.json
  def create
    @tarea = Tarea.new(tarea_params)

    respond_to do |format|
      if @tarea.save
        format.html { redirect_to @tarea, notice: 'Tarea was successfully created.' }
        format.json { render :show, status: :created, location: @tarea }
      else
        format.html { render :new }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tareas/1
  # PATCH/PUT /tareas/1.json
  def update
    respond_to do |format|
      if @tarea.update(tarea_params)
        format.html { redirect_to @tarea, notice: 'Tarea was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarea }
      else
        format.html { render :edit }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tareas/1
  # DELETE /tareas/1.json
  def destroy
    @tarea.destroy
    respond_to do |format|
      format.html { redirect_to tareas_url, notice: 'Tarea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarea
      @tarea = Tarea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tarea_params
      params.require(:tarea).permit(:title, :desc, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg  navbar-light bg-dark navbar-dark ">


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse container-fluid navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar navbar-nav mr-auto">
          <a class="navbar-brand" href="<%= root_path %>">Las Tareas</a>
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link">
              <%= current_user.email %>
          </a>
        </li>
          <a class="nav-link" href="<%= destroy_user_session_path %>" data-method="delete"> Log out </a>
      <% else %>
          <a class="nav-link " href="<%= new_user_session_path %>"> Login </a>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tareaprueba</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if notice.present?%>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
    <% end %>

    <% if alert.present? %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
    <% end %>

    <%= yield %>


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

  </body>
</html>

app/views/tareas/_form.html.erb
<%= form_with(model: tarea, local: true) do |form| %>
  <% if tarea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tarea.errors.count, "error") %> prohibited this tarea from being saved:</h2>

      <ul>
        <% tarea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tareas/_tarea.html.erb
<div class="card" style="width: 18rem;">

  <img src="<%= tarea.photo %>" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= tarea.title %></h5>
    <p class="card-text"><%= tarea.desc %></p>
    <% if user_signed_in? %>
          <% if tarea.users.include?(current_user) %>
            <%= link_to "Cancelar", completar_path(tarea), class:'btn btn-danger' %>
            <% else %>
            <%= link_to "Completar", completar_path(tarea), class:'btn btn-primary' %>
          <% end %>
      <%end %>

  <%= link_to 'Ver Mas', tarea, :class => "btn btn-success txt-danger"%>

   </div>
</div>

app/views/tareas/edit.html.erb
<h1>Editing Tarea</h1>

<%= render 'form', tarea: @tarea %>

<%= link_to 'Show', @tarea %> |
<%= link_to 'Back', tareas_path %>

app/views/tareas/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Tareas</h1>

    <div class="container">
  <div class="row">
    <% @tareas.each do |tarea| %>
    <div class="col-sm">
      <%= render tarea %>
    </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Tarea', new_tarea_path %>

app/views/tareas/new.html.erb
<h1>New Tarea</h1>

<%= render 'form', tarea: @tarea %>

<%= link_to 'Back', tareas_path %>

app/views/tareas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tarea.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @tarea.desc %>
</p>

<p>
  <strong>Photo:</strong>
    <img src="<%= @tarea.photo %>" class="card-img-top" alt="...">
</p>

<h2>usuario</h2>
<% @tarea.users.each do |u| %>
  <%= u.email %>
<% end %>
<h2>ranking</h2>
<% @ranking.each do |u| %>
  <%= u.email %>
<% end %>

<%= link_to 'Edit', edit_tarea_path(@tarea) %> |
<%= link_to 'Back', tareas_path %>